---
# file: idrac.yml

- hosts: localhost
  sudo: yes
  tasks:
  - name: Install wsman
    yum: name=wsmancli state=present
    tags:
      - idrac-facts
      - idrac-alerts
      - idrac-firmware
      - idrac-storage
      - idrac-os-install

  - debug: var={{share_type}}

- hosts: localhost
  sudo: yes
  
  roles:
    - { role: idrac/local, tags: "idrac-local" }

- hosts: idracs
  gather_facts: False
  sudo: yes

  roles:
    - { role: idrac/facts, tags: [ "idrac-facts", "idrac-alerts", "idrac-firmware", "idrac-storage", "idrac-os-install" ] }
    - { role: idrac/alerts, tags: "idrac-alerts" }
    - { role: idrac/firmware, tags: "idrac-firmware" }
    #- { role: idrac/storage, tags: "idrac-storage" }
    #- { role: idrac/os-install, tags: "idrac-os-install" }
